### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp2-visiteur-borghino-chomarat-tp2#1]
- Pouvez vous m'expliquer le cas d'utilisation du pattern visiteur ?

- On range les choses en packages (:warning:  les packages en java c'est en minuscule)

- Je suis pas sur que votre priorité marche, pourriez vous me le démontrer sur 1 ou deux exemples ?

Sinon c'est pas mal 👍

**Comment by hugochmt** [comment]
- On utilise le pattern Visiteur dans notre cas car nous voulons effectuer des opérations sur différents types d'objets (addition, multiplication...) sans les modifier. Donc on effectue ces opérations par le biais des différents visiteurs correspondant aux différentes opérations.

- Concernant la priorité, si on prend par exemple `new Multiplication( new Constante(7), new Addition(new Constante(2), new Constante(3)));`, on obtient bien `7*(2+3)`.
Pareil pour `new Multiplication( new Addition(new Constante(3), new Constante(4)), new Addition(new Constante(2), new Constante(5)));`, qui nous donne bien `(3+4)*(2+5)`

**Comment by Slashgear** [comment]
- [ ] il me manque le découpage en package et c'est bon

**Comment by Vipeross** [comment]
Bonjour, pardon pour la réponse tardive.
Nous avons ajouté un découpage en package assez simple, un regroupant nos visiteurs et un deuxième contenant les diférentes opérations et autre structure du TP.

Pour représenter 7*2+3 en notation infixe il faudra définir l'opération de la manière suivante : 
`Addition racine =  new Addition(new Multiplication(new Constante(7), new Constante(2)), new Constante(3));`
C'est une addition entre le produit de 7 par 2 et la constante 3. Nous obtenons bien "7*2+3"
